CREATE TABLE IF NOT EXISTS shirts (
	id INTEGER PRIMARY KEY,
	style TEXT,
	color TEXT,
	instock INTEGER,
	price INTEGER,
	shirt_image TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
	id INTEGER PRIMARY KEY,
	email TEXT,
	shirt_id INTEGER,
	quantity INTEGER,
	status TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);